// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:g_sync/src/functions/objects/models/download/download_table.dart';
import 'package:g_sync/src/functions/objects/models/upload/upload_table.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GSDownloadDataAdapter());
    registerAdapter(GSDownloadTableAdapter());
    registerAdapter(GSUploadDataAdapter());
    registerAdapter(GSUploadTableAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GSDownloadDataAdapter());
    registerAdapter(GSDownloadTableAdapter());
    registerAdapter(GSUploadDataAdapter());
    registerAdapter(GSUploadTableAdapter());
  }
}
